### ISSUE TITLE
ProjectConfigurator shortcut it's created by default in the desktop not in the folder described

### ISSUE THREAD

**Issue by CppHotReload** [awsdocs/amazon-lumberyard-user-guide#23]
The executable is in the folder _lumberyard_version_\dev\Bin64vc141 and the shortcut is created on the desktop not in the described path: Navigate to the lumberyard_version\dev\Tools\LmbrSetup\Win\ directory and then start ProjectConfigurator.

**Comment by sptramer** [comment]
Hello there, this issue is being closed for the following reason -

**Amazon Lumberyard is no longer offered. We recommend Open 3D Engine, Lumberyard’s Apache-licensed successor. O3DE is maintained by the open-source community, including developers from Adobe, AWS, Epic, Microsoft, Intel, Lightspeed Studios, Niantic, and others. Visit O3DE's [website](https://www.o3de.org/ "website"), [Discord](https://discord.gg/o3de), and [Github](https://github.com/o3de/o3de).**
