### ISSUE TITLE
Not found `Build_AssetBundler_AuxiliaryContent_PC.bat`

### ISSUE THREAD

**Issue by syrokomskyi** [awsdocs/amazon-lumberyard-user-guide#24]
Guys, LY 1.23 from ofsite, tutorial [Simple Asset Bundling and Release Tutorial](https://github.com/awsdocs/amazon-lumberyard-user-guide/blob/master/doc_source/asset-bundler-tutorial-simple.md).

I can't find the file `Build_AssetBundler_AuxiliaryContent_PC.bat`. Many tutorials has a reference to it:

![изображение](https://user-images.githubusercontent.com/311074/77085113-8e6cd080-6a08-11ea-9e4a-310712d00a9f.png)

**Comment by syrokomskyi** [comment]
I found it in the [release description](https://docs.aws.amazon.com/lumberyard/latest/releasenotes/lumberyard-v1.22.html). PR is sent out.

Oh, guys, seriously raise an entry threshold to **Lumberyard** when you throw out links like that(

**Comment by sptramer** [comment]
Hello there, this issue is being closed for the following reason -

**Amazon Lumberyard is no longer offered. We recommend Open 3D Engine, Lumberyard’s Apache-licensed successor. O3DE is maintained by the open-source community, including developers from Adobe, AWS, Epic, Microsoft, Intel, Lightspeed Studios, Niantic, and others. Visit O3DE's [website](https://www.o3de.org/ "website"), [Discord](https://discord.gg/o3de), and [Github](https://github.com/o3de/o3de).**
